### ISSUE TITLE
When the application starts, you have 3 empty columns: "Todo", "In progress", "Done"

### ISSUE THREAD

**Issue by krlenell** [david-diep/kanban-hackathon#5]
- [x] Create component for overall page
- [x] make state an array which contains the names of columns.  Initially this is Todo, In progress, Done
- [ ] Create component for column.  Column can take in a prop for title
- [ ] Display columns, mapping page state as titles for columns
